import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.Serializable;
import java.io.UnsupportedEncodingException;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collection;
import java.util.Map;
import java.util.regex.Pattern;

import com.esotericsoftware.jsonbeans.Json;
import com.esotericsoftware.jsonbeans.OutputType;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    		
    		
    public static void main(String[] args) {
    	
    	Collection<Partido> PartidosTemporada = new ArrayList<>();
    	
    	   try (BufferedReader reader = new BufferedReader(new FileReader("C:\\desarrolloI\\eclipse-workspace\\Datos_Deportivos3\\SP1.csv"))){
   			String linea = ""; 				
   			String lineaAux = reader.readLine();
   			String [] arrayAux = lineaAux.split(",");
//   			SimpleDateFormat formatear = new SimpleDateFormat("dd/MM/yy");
   	   				
   			String Division = arrayAux[0];
   			
   			
   			while((linea = reader.readLine()) != null) {
   				String[] miarray = linea.split(",");
   				if (miarray[0] == Division) {
   					System.out.println("Es un div");
   				} else {
   					Partido partido = new Partido(miarray[0],miarray[1], miarray[2],miarray[3],miarray[7]);
   					System.out.println(partido.toString());
   					PartidosTemporada.add(partido);   					
   				}
   			}
   		} catch (UnsupportedEncodingException | FileNotFoundException e) {
   			e.printStackTrace();
   		} catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
   		
    	
        // Serializador JSON
//        Json json = new Json(OutputType.json);

//        // Objeto para serializar inicializado
//        Object obj = new Object() {
//            int[] numeros;
//            String texto;
//            Boolean prueba;
//
//            Object init() {
//                numeros = new int[] { 1, 2, 3 };
//                texto = "Mi texto";
//                prueba = false;
//
//                return this;
//
//            }
//        }.init();

    
        
        // Salida por consola serializada en formato facil de leer
//        System.out.println(json.prettyPrint(obj));
//        
//        Participante.mapaParticipantes.put("LEGANES",new Participante("Leganés"));
//        Participante.mapaParticipantes.put("RMADRID",new Participante("Real Madrid"));        
    }



	private static Date SimpleDateFormat(String string) {
		String fechaPartido = string;
		
		
		return null;
	}
    

    
}
